services:
  app1:
    build: ./services
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - unstable-service

  app2:
    build: ./services
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - unstable-service

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2

  unstable-service:
    build:
      context: ./services
      dockerfile: Dockerfile
    command: node unstable.js
    ports:
      - "4000:4000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - unstable-service
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3000" 
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana-data:
