global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "microservice"
    static_configs:
      - targets: ["nginx:80"]
  
  - job_name: "unstable-service"
    static_configs:
      - targets: ["unstable-service:4000"]
